site_name: maximo-cpi
site_url: https://ibm-mas.github.io/mcpi

repo_name: GitHub
repo_url: https://github.com/ibm-mas/mcpi
edit_uri: blob/master/docs/

nav:
  - 'Maximo-CPI User Guide':
    - 'Running Maximo-CPI': maximo-cpi/running-maximo-cpi.md
    - 'Harmony Checker Data Collection': maximo-cpi/data-collection.md
    - 'Harmony Checker Data Review': maximo-cpi/data-review.md
    - 'Custom Metric Collection': maximo-cpi/custom-metric-collection.md
    - 'Logging Collection': logging.md
    - 'Frequently Asked Questions': faq.md
    #- 'Node Balance Data Collection': maximo-cpi/nb/nb.md
    #- 'Root Cause Analysis': maximo-cpi/rca/rca.md
    #- 'Database Metric Collection': maximo-cpi/db/db.md
    #- 'Maximo-CPI Video Collection': maximo-cpi/video/mhc-video.md
  - 'Changelog': changelog.md
  - 'Diagnosis Handbook':
    - 'Diagnosis Tool': diagnosis/diagnostic-tool.md
    - 'Diagnosis Process': diagnosis/diagnostic-process.md
  - 'Reference':
    - 'Maximo Performance Wiki (Public)': https://ibm-mas.github.io/mas-performance/

  - 'Reference':
    - 'Maximo Performance Wiki (Public)': https://ibm-mas.github.io/mas-performance/


theme:
  name: readthedocs 
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
  feature:
    - navigation.instant

extra_css:
  - extra.css

plugins:
  - mkdocs-video

markdown_extensions:
  - toc:
      permalink: 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 