site_name: maximo-cpi
site_url: https://ibm-mas.github.io/mcpi

repo_name: GitHub
repo_url: https://github.com/ibm-mas/mcpi
edit_uri: blob/master/docs/

nav:
  - 'Maximo-CPI User Guide': index.md
  - 'Reference':
    - 'Maximo Performance Wiki (Public)': https://ibm-mas.github.io/mas-performance/


theme:
  name: readthedocs 
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
  feature:
    - navigation.instant

extra_css:
  - extra.css

plugins:
  - mkdocs-video

markdown_extensions:
  - toc:
      permalink: 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 