---
apiVersion: v1
kind: Namespace
metadata:
  name: maximo-cpi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpi
  namespace: maximo-cpi
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcpi-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: mcpi
    namespace: maximo-cpi
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: mcpi-scc
runAsUser:
  type: MustRunAs
  uid: 1002
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: false
volumes:
- '*'
users:
- system:serviceaccount:maximo-cpi:default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpi-deployment
  namespace: maximo-cpi
  labels:
    app: mcpi
spec:
  replicas: 1
  imagePullPolicy: Always
  selector:
    matchLabels:
      app: mcpi
  template:
    metadata:
      labels:
        app: mcpi
    spec:
      securityContext:
        runAsUser: 1002  # no specify, the openshift uses the restricted by default
      serviceAccountName: mcpi
      containers:
        - name: mcpi
          image: 'quay.io/ibmmas/mcpi:latest'
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: "30Gi"             
          env:
            - name: INCLUSTER
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mcpi-service
  namespace: maximo-cpi
spec:
  selector:
    app: mcpi
  ports:
    - name: viewer-port
      protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mcpi-viewer-route
  namespace: maximo-cpi
  labels: {}
spec:
  to:
    kind: Service
    name: mcpi-service
    weight: 100
  port:
    targetPort: viewer-port
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: mcpi-rsyslog
  namespace: maximo-cpi
spec:
  type: NodePort  
  selector:
    app: mcpi
  ports:
    - name: rsyslog-tcp
      protocol: TCP
      port: 10514
      targetPort: 10514
    - name: rsyslog-udp
      protocol: UDP
      port: 10514
      targetPort: 10514