apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: masmanage-stats
  namespace: maximo-cpi
spec:
  namespaceSelector:
    matchNames:
      - maximo-cpi
  podMetricsEndpoints:
    - interval: 60s
      path: /collectmetrics?name=masmanage-stats
      port: http
      scrapeTimeout: 60s
  selector:
    matchLabels:
      app: mcpi