{
 "title": "maximo-cpi",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "mas_core_ns",
    "label": "MAS Core NameSpace",
    "query": {
     "query": "label_values(mas_core_request,mas_namespace)"
    }
   },
   {
    "name": "mas_manage_ns",
    "label": "MAS Manage Namespace",
    "query": {
     "query": "label_values(mas_manage_request,mas_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MAS Core HTTP Request Per Min", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Request By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_request{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "Avg Response By Service (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_responsetime{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}/mas_core_request{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of Request By Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mas_core_request{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{mas_pod}}"
    }
   ]
  },
  {
   "title": "Avg Response By Pod (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mas_core_responsetime{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}/mas_core_request{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of Request Over 1-Second By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "mas_core_request_over1sec{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of Request Over 1 Second By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "mas_core_request_over1sec{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_core_ns\"}",
     "legendFormat": "{{mas-namespace}}:{{mas_pod}}"
    }
   ]
  },
  {
   "title": "MAS Manage HTTP Request Per Min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "# of Request By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "mas_manage_request{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "Avg Response By Service (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "mas_manage_responsetime{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}/mas_manage_request{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of Request By Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mas_manage_request{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{mas_pod}}"
    }
   ]
  },
  {
   "title": "Avg Response By Pod (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "mas_manage_responsetime{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}/mas_manage_request{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of Request Over 2-Second By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "mas_manage_request_over2sec{mas_pod=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{service}}"
    }
   ]
  },
  {
   "title": "# of  Request Over 2-Second By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "mas_manage_request_over2sec{mas_pod!=\"\",service!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_namespace}}:{{mas_pod}}"
    }
   ]
  },
  {
   "title": "# of Maximo Long Run Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "mas_manage_lrq{mas_pod!=\"\",mas_namespace=~\"$mas_manage_ns\"}",
     "legendFormat": "{{mas_pod}}"
    }
   ]
  }
 ]
}