{
 "title": "maximo-cpi",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "MAS Core HTTP Request Per Min", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Request By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_request{mas_pod=\"\",service!=\"\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# of Request Over 1-Second By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_request_over1sec{mas_pod=\"\",service!=\"\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# of Request By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_request{mas_pod!=\"\",service!=\"\"}",
     "legendFormat": "{{mas_pod}}"
    }
   ]
  },
  {
   "title": "# of Request Over 1 Second By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "mas_core_request_over1sec{mas_pod!=\"\",service!=\"\"}",
     "legendFormat": "{{mas_pod}}"
    }
   ]
  },
  {
   "title": "MAS Manage HTTP Request Per Min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "# of Request By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "mas_manage_request{mas_pod=\"\",service!=\"\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# of Request Over 2-Second By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "mas_manage_request_over2sec{mas_pod=\"\",service!=\"\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# of Request By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "mas_manage_request{mas_pod!=\"\",service!=\"\"}",
     "legendFormat": "{{mas_pod}}"
    }
   ]
  },
  {
   "title": "# of  Request Over 2-Second By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "mas_manage_request_over2sec{mas_pod!=\"\",service!=\"\"}",
     "legendFormat": "{{mas_pod}}"
    }
   ]
  },
  {
   "title": "# of Request By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mas_manage_lrq", "legendFormat": "{{mas_pod}}" }
   ]
  }
 ]
}